### ISSUE TITLE
Dog spawning and then disappears

### ISSUE THREAD

**Issue by PCL-CrisKolkman** [GouveiaXS/angelicxs-policeK9#5]
Hello,

I’m trying to get this to work (QBCore), but it was in first place very difficult to even get a third eye on the set location (even when I have the job not as required) and when I get the K9, the dog appears for a second and then is gone again.

No errors or whatever in the F8 console.

**Comment by GouveiaXS** [comment]
it was in first place very difficult to even get a third eye on the set location

You can only third eye object/entities etc. those will change based on where you are and if you are using any MLOs and their own setups. This is the standard functionality of whatever third eye system you are using.

    when I get the K9, the dog appears for a second and then is gone again.

You have a conflicting script which is deleting/removing the model used for the dog. This is most likely due to a blacklisting/whitelisting system you may be using. Either resolve the conflict with the standard model or change the dog model from its default which can be changed in line 155:
local hash = HashGrabber('a_c_shepherd')
